## I-Reports

- `rishadblack/i-reports` builds paginated, filterable reports with print, PDF (mpdf), Excel and CSV export from one Blade view, viewed through a Bootstrap 5.3 Livewire component. Activate the `i-reports-development` skill whenever you create, edit, or test a report.
- A report is a class that extends `Rishadblack\IReports\BaseReportController` and implements `builder(): Illuminate\Database\Eloquent\Builder`, `configure(): void` and `columns(): array`. Scaffold one with `php artisan make:report {name}`. Do not write controllers, routes, or export classes for reports; the package's `i-reports.view` route and `<livewire:i-reports.report-viewer report="..." />` handle viewing and exporting.
- Report names resolve to classes as `{livewire.class_namespace}\{i-reports.report_namespace}\{StudlyName}{i-reports.report_suffix}` (this app: `users` → `App\Livewire\Reports\UsersReport`). The view is derived from the class: `App\Livewire\Reports\UsersReport` → `resources/views/livewire/reports/users-report.blade.php`.
- Report views use the `x-i-reports::*` components (`layout`, `table`, `thead`, `tbody`, `grouped-tbody`, `tr`, `th`, `td`, `aggregates`, `page-break`) and loop over `$columns` and `$datas`. Do not call `$datas->links()`; the viewer paginates.
- Define columns with `Rishadblack\IReports\Views\Column::make('Title', 'field')`, using `relation.field` for `BelongsTo`/`HasOne`/`MorphOne` relations. Use the column types (`money()`, `date()`, `boolean()`, `badge()`, ...), `sortable()`, `searchable()`, `hideIn()` and aggregates (`sum()`, ...). Cell output is escaped; call `->html()` only when `format()` returns trusted markup.
- Define filters with `Rishadblack\IReports\Views\Filter::make('Title', 'key')` plus a type (`select()`, `multiSelect()`, `dateRange()`, `numberRange()`, `boolean()`, `component()`), and either `->column('table.col')` for the automatic constraint or `->filter(fn (Builder $query, $value) => ...)`. Qualify columns with the table name, because relation columns add joins.
- `builder()` and `authorize()` are the authorization boundary. The report route always requires a user-bound token and uses `['web']` middleware by default; add `auth` in `i-reports.route_middleware` for private data.
