## I-Reports

- `rishadblack/i-reports` builds paginated, filterable reports from one class (a Blade view is optional), shown in a Bootstrap 5.3 Livewire viewer with search, filters, sorting, a column picker, saved views and print, PDF (mPDF), Excel and CSV export. Activate the `i-reports-development` skill whenever you create, edit, export or test a report.
- A report extends `Rishadblack\IReports\BaseReportController` and implements `builder(): Illuminate\Database\Eloquent\Builder`, `configure(): void` (settings only), `columns(): array` and optionally `filters(): array`. Scaffold one with `php artisan make:report {name}`. Show it with `<livewire:i-reports.report-viewer report="{name}" />`. Do not write controllers, routes, export classes or JavaScript for reports.
- Reports render through the package's default grid view unless the app has a view at the conventional path. Do not create a report view for a plain grid; when custom markup is needed, copy the default with `php artisan i-reports:view {name}` (or scaffold with `make:report {name} --view`) and customize the copy.
- Report names resolve to `{livewire.class_namespace}\{i-reports.report_namespace}\{StudlyName}{i-reports.report_suffix}` (`users` → `App\Livewire\Reports\UsersReport`, `sales.daily` → `App\Livewire\Reports\Sales\DailyReport`). The view path follows the class (`resources/views/livewire/reports/users-report.blade.php`). It uses `x-i-reports::layout`, `table`, `thead`, `tr`, `th`, `tbody` and `<x-i-reports::rows :rows="$datas" />`. Never call `$datas->links()`.
- Columns: `Column::make('Title', 'field')`, with `relation.field` for `BelongsTo`/`HasOne`/`MorphOne`. Types are optional (`number()`, `money()`, `date()`, `datetime()`, `boolean()`, `badge()`, `link()`, `image()`). Use them only for real numbers, amounts and dates, never for IDs or phone numbers; use `->align('right')` for those. Aggregates are `sum()`, `avg()`, `count()`, `min()`, `max()`. Output is escaped; add `->html()` only for trusted markup.
- Users can hide columns, and hidden columns are dropped from the SQL `SELECT`. Mark a column `->alwaysSelect()` when `map()` or another column's `format()` reads it. Use `->hiddenByDefault()` for optional columns and `->hideable(false)` for required ones.
- Filters: `Filter::make('Title', 'key')` with a type (`text()`, `select()`, `multiSelect()`, `date()`, `dateRange()`, `number()`, `numberRange()`, `boolean()`, `component()`, `bladeComponent()`), plus `->column('table.col')` or `->filter(fn (Builder $query, $value) => ...)`. Add `->displayUsing(fn ($id) => ...)` to id-based filters so chips and export headers show names. Always qualify columns with the table name, because relation columns add joins.
- Print and PDF open a page setup dialog (paper, orientation, font size, scale). Defaults come from `setPaperSize()`, `setOrientation()`, `setFontSize()` and `setScale()` or `config('i-reports.page_setup')`. Prints above `print.split_after` rows open in parts of `print.rows_per_part` rows with Previous / Next. Every export gets the header and footer from `config('i-reports.branding')` (name, tagline, address, contact, logo, footer_note).
- When the report's Blade view computes values (running balances, debit/credit, nested rows, `<tfoot>` totals), call `$this->setExportSource('view')` (or set config `export_source` to `view`). Otherwise Excel, CSV, streamed PDF and split prints are built from the columns and miss those values.
- With `i-reports.queue.enabled` (run `php artisan migrate` and a queue worker), large exports run in the background. The viewer tracks them by polling, or over Reverb/Pusher when `queue.realtime` is `broadcast`.
- `builder()` and `authorize()` are the authorization boundary. Scope `builder()` to the user or tenant on shared data, and add `auth` to `i-reports.route_middleware` for private reports. Report URLs carry a short-lived, user-bound token; create test tokens with `(new Rishadblack\IReports\Helpers\RequestHelper([...]))->generateToken()` as the acting user.
